baseURL = "https://sasha.johnsey.me/"
languageCode = "en-us"
title = "Sasha Angel Johnsey"
theme = "pulp"
canonifyurls = true
hasCJKLanguage = true
publishDir = "docs"
# googleAnalytics = "{your tracking code}"

[taxonomies]
  series = "series"

[params]
    author = "Sasha Angel Johnsey"
    avatar = "avatar.png"
    favicon = "favicon.ico"
    publicationYear = "2019"
    listPageDateFormat = "January, 2006"
    singlePageDateFormat = "January 2, 2006"

[outputs]
    section = ["JSON", "HTML"]
